@startuml
Actor Utilisateur As U
Participant Application As A

U->A: l'utilisateur cherche un pseudo
Alt Utilisateur non existant
A->>U: indique qu'il y a aucun utilisateur
Else Si utilisateur trouvé
A->>U: affiche l'utilisateur
end

@enduml
